// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWHaFA2gsFagvY51I1fZaadzajvvqmSB8',
    appId: '1:853832968848:web:06eb3bca6f82e79f3ec615',
    messagingSenderId: '853832968848',
    projectId: 'baii-ccea6',
    authDomain: 'baii-ccea6.firebaseapp.com',
    storageBucket: 'baii-ccea6.firebasestorage.app',
    measurementId: 'G-9PVK5ZS3X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJqaSBKRmfCLXCxE-prnhCEdPHbx4SP30',
    appId: '1:853832968848:android:99548d61d866c7ca3ec615',
    messagingSenderId: '853832968848',
    projectId: 'baii-ccea6',
    storageBucket: 'baii-ccea6.firebasestorage.app',
  );
}
